In [ ]:
### starting over, making a result column with 0 and 1

In [112]:
import pandas as pd 

# show all columns
pd.set_option('display.max_columns', None)

df = pd.read_csv("atp_matches_2023.csv", parse_dates = ['tourney_date'])\
    .sort_values(by='tourney_date')
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,2023-01-02,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
78,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,270,200615,NaN,Q,Alexei Popyrin,R,196.0,AUS,23.4,200000,2.0,NaN,Felix Auger Aliassime,R,193.0,CAN,22.4,6-4 7-6(5),3,R32,114.0,11.0,2.0,67.0,45.0,35.0,13.0,11.0,1.0,2.0,7.0,2.0,66.0,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0
77,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,271,106218,NaN,NaN,Marcos Giron,R,180.0,USA,29.4,104755,NaN,NaN,Richard Gasquet,R,183.0,FRA,36.5,7-6(5) 6-7(6) 7-5,3,R32,177.0,13.0,2.0,110.0,76.0,59.0,23.0,18.0,2.0,3.0,10.0,4.0,139.0,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0
76,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,272,111456,NaN,NaN,Mackenzie Mcdonald,R,178.0,USA,27.7,123755,NaN,NaN,Daniel Elahi Galan,R,191.0,COL,26.5,6-3 0-0 RET,3,R32,40.0,4.0,1.0,20.0,14.0,14.0,2.0,4.0,0.0,0.0,2.0,1.0,39.0,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0
75,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,273,106415,NaN,NaN,Yoshihito Nishioka,L,170.0,JPN,27.2,208029,5.0,NaN,Holger Rune,R,188.0,DEN,19.6,2-6 6-4 6-4,3,R32,125.0,0.0,8.0,86.0,54.0,36.0,16.0,14.0,5.0,9.0,14.0,8.0,95.0,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,290,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,4-2 2-4 4-3(7) 4-1,5,RR,108.0,13.0,2.0,74.0,45.0,35.0,15.0,12.0,6.0,7.0,4.0,3.0,70.0,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0
2765,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,286,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,3-4(6) 4-2 4-3(5) 4-2,5,RR,92.0,18.0,1.0,71.0,56.0,49.0,8.0,12.0,3.0,3.0,9.0,2.0,76.0,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0
2764,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,287,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,210506,4.0,NaN,Alex Michelsen,R,193.0,USA,19.2,4-2 1-4 4-0 4-0,5,RR,67.0,7.0,2.0,51.0,34.0,25.0,10.0,9.0,3.0,4.0,2.0,1.0,55.0,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0
2762,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,289,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,4-3(5) 3-4(5) 4-1 4-1,5,RR,114.0,9.0,3.0,81.0,62.0,40.0,5.0,11.0,15.0,17.0,5.0,3.0,76.0,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0
2759,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,292,208134,7.0,NaN,Luca Nardi,R,185.0,ITA,20.3,207925,5.0,NaN,Flavio Cobolli,R,183.0,ITA,21.5,3-4(4) 4-2 4-3(1) 1-4 4-3(3),5,RR,133.0,5.0,0.0,93.0,67.0,51.0,14.0,14.0,5.0,7.0,3.0,2.0,97.0,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0

In [113]:
# Create two dataframes: one for where top 20 players have won and one where they have lost
wins_df = df.copy()

# For wins, I will first make a result column with 1 or 0, in this df all rows in the result column will have 1
wins_df['result'] = 1

#also adding the name of the player who won as the main player for that match
wins_df['player'] = wins_df['winner_name']

#calculating rate of 1st serves won
wins_df['w_rate_1stWon'] = wins_df['w_1stWon'] / wins_df['w_1stIn'].replace(0, pd.NA)

#calculating rate of break points saved (stat explained in memo)
wins_df['w_bpSaved_rate'] = wins_df['w_bpSaved'] / wins_df['w_bpFaced'].replace(0, pd.NA)

# for every player, i also want return points stats, and these I will get from the loser's service points stats
wins_df['w_return_points_won'] = wins_df['l_svpt'] - wins_df['l_1stWon'] - wins_df['l_2ndWon'] #calculating how many return points they faced
wins_df['w_return_rate'] = wins_df['w_return_points_won'] / wins_df['l_svpt'].replace(0, pd.NA) #rate of return points won by winner


#Doing the same calculation for the matches the players lost
losses_df = df.copy()
losses_df['result'] = 0
losses_df['player'] = losses_df['loser_name']
losses_df['l_rate_1stWon'] = losses_df['l_1stWon'] / losses_df['l_1stIn'].replace(0, pd.NA)
losses_df['l_bpSaved_rate'] = losses_df['l_bpSaved'] / losses_df['l_bpFaced'].replace(0, pd.NA)
losses_df['l_return_points_won'] = losses_df['w_svpt'] - losses_df['w_1stWon'] - losses_df['w_2ndWon']
losses_df['l_return_rate'] = losses_df['l_return_points_won'] / losses_df['w_svpt'].replace(0, pd.NA)

#combining the two dataframes so now i have a new dataset of all top 20 players and the matches they won and lost in 2023
combined_df = pd.concat([wins_df, losses_df], ignore_index=True)

combined_df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,result,player,w_rate_1stWon,w_bpSaved_rate,w_return_points_won,w_return_rate,l_rate_1stWon,l_bpSaved_rate,l_return_points_won,l_return_rate
0,2023-9900,United Cup,Hard,18,A,2023-01-02,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0,1,Taylor Fritz,0.865385,<NA>,35.0,0.360825,NaN,NaN,NaN,NaN
1,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,270,200615,NaN,Q,Alexei Popyrin,R,196.0,AUS,23.4,200000,2.0,NaN,Felix Auger Aliassime,R,193.0,CAN,22.4,6-4 7-6(5),3,R32,114.0,11.0,2.0,67.0,45.0,35.0,13.0,11.0,1.0,2.0,7.0,2.0,66.0,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0,1,Alexei Popyrin,0.777778,0.5,22.0,0.333333,NaN,NaN,NaN,NaN
2,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,271,106218,NaN,NaN,Marcos Giron,R,180.0,USA,29.4,104755,NaN,NaN,Richard Gasquet,R,183.0,FRA,36.5,7-6(5) 6-7(6) 7-5,3,R32,177.0,13.0,2.0,110.0,76.0,59.0,23.0,18.0,2.0,3.0,10.0,4.0,139.0,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0,1,Marcos Giron,0.776316,0.666667,50.0,0.359712,NaN,NaN,NaN,NaN
3,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,272,111456,NaN,NaN,Mackenzie Mcdonald,R,178.0,USA,27.7,123755,NaN,NaN,Daniel Elahi Galan,R,191.0,COL,26.5,6-3 0-0 RET,3,R32,40.0,4.0,1.0,20.0,14.0,14.0,2.0,4.0,0.0,0.0,2.0,1.0,39.0,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0,1,Mackenzie Mcdonald,1.000000,<NA>,17.0,0.435897,NaN,NaN,NaN,NaN
4,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,273,106415,NaN,NaN,Yoshihito Nishioka,L,170.0,JPN,27.2,208029,5.0,NaN,Holger Rune,R,188.0,DEN,19.6,2-6 6-4 6-4,3,R32,125.0,0.0,8.0,86.0,54.0,36.0,16.0,14.0,5.0,9.0,14.0,8.0,95.0,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0,1,Yoshihito Nishioka,0.666667,0.555556,39.0,0.410526,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,290,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,4-2 2-4 4-3(7) 4-1,5,RR,108.0,13.0,2.0,74.0,45.0,35.0,15.0,12.0,6.0,7.0,4.0,3.0,70.0,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0,0,Luca Van Assche,NaN,NaN,NaN,NaN,0.674419,0.818182,24.0,0.324324
5968,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,286,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,3-4(6) 4-2 4-3(5) 4-2,5,RR,92.0,18.0,1.0,71.0,56.0,49.0,8.0,12.0,3.0,3.0,9.0,2.0,76.0,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0,0,Abedallah Shelbayh,NaN,NaN,NaN,NaN,0.720000,0.0,14.0,0.197183
5969,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,287,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,210506,4.0,NaN,Alex Michelsen,R,193.0,USA,19.2,4-2 1-4 4-0 4-0,5,RR,67.0,7.0,2.0,51.0,34.0,25.0,10.0,9.0,3.0,4.0,2.0,1.0,55.0,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0,0,Alex Michelsen,NaN,NaN,NaN,NaN,0.594595,0.5,16.0,0.313725
5970,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,289,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,4-3(5) 3-4(5) 4-1 4-1,5,RR,114.0,9.0,3.0,81.0,62.0,40.0,5.0,11.0,15.0,17.0,5.0,3.0,76.0,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0,0,Abedallah Shelbayh,NaN,NaN,NaN,NaN,0.682927,0.5,36.0,0.444444
5971,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,292,208134,7.0,NaN,Luca Nardi,R,185.0,ITA,20.3,207925,5.0,NaN,Flavio Cobolli,R,183.0,ITA,21.5,3-4(4) 4-2 4-3(1) 1-4 4-3(3),5,RR,133.0,5.0,0.0,93.0,67.0,51.0,14.0,14.0,5.0,7.0,3.0,2.0,97.0,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0,0,Flavio Cobolli,NaN,NaN,NaN,NaN,0.807692,0.6,28.0,0.301075

In [114]:
from tqdm.auto import tqdm
tqdm.pandas()

In [115]:
predictors = []

for index, match in tqdm(combined_df.iterrows(), total=len(combined_df)):

    match_date = match['tourney_date']
    
    # Filter all matches that happened before this one
    player = match['player']
    previous_matches = combined_df[
        (combined_df['tourney_date'] < match_date) &
        (combined_df['player'] == player)
        ]

    
    # Count previous wins using the 'result' column
    

    # Average rate_1stWon from previous matches. taking the mean value because count or sum will not be right, like for the previous one 
    w_rate_1stWon_so_far = previous_matches['w_rate_1stWon'].mean()
    l_rate_1stWon_so_far = previous_matches['l_rate_1stWon'].mean()
    # avg_rate_1stWon_so_far = avg_rate_1stWon_so_far if not pd.isna(avg_rate_1stWon_so_far) else 0

    #same for bpSaved_rate from previous matches
    w_bpSaved_rate_so_far = previous_matches['w_bpSaved_rate'].mean()
    l_bpSaved_rate_so_far = previous_matches['l_bpSaved_rate'].mean()
    # avg_bpSaved_rate_so_far = avg_bpSaved_rate_so_far if not pd.isna(avg_bpSaved_rate_so_far) else 0

    #same for return_rate
    w_return_rate_so_far = previous_matches['w_return_rate'].mean()
    l_return_rate_so_far = previous_matches['l_return_rate'].mean()
    # avg_return_rate_so_far = avg_return_rate_so_far if not pd.isna(avg_return_rate_so_far) else 0

    predictors.append({
       'w_prev_rate_1stWon_avg': w_rate_1stWon_so_far,
        'l_prev_rate_1stWon_avg': l_rate_1stWon_so_far,
        'w_prev_bpSaved_rate': w_bpSaved_rate_so_far,
        'l_prev_bpSaved_rate': l_bpSaved_rate_so_far,
        'w_prev_return_rate': w_return_rate_so_far,
        'l_prev_return_rate': l_return_rate_so_far,   
    })

predictors_df = pd.DataFrame(predictors)
predictors_df

  0%|          | 0/5972 [00:00<?, ?it/s]

,w_prev_rate_1stWon_avg,l_prev_rate_1stWon_avg,w_prev_bpSaved_rate,l_prev_bpSaved_rate,w_prev_return_rate,l_prev_return_rate
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
5967,0.708991,0.654708,0.602251,0.554127,0.425133,0.319388
5968,0.676136,0.660817,0.649351,0.588889,0.525440,0.316718
5969,0.748812,0.658961,0.721088,0.517316,0.414623,0.262414
5970,0.676136,0.660817,0.649351,0.588889,0.525440,0.316718
5971,0.750897,0.646003,0.783333,0.411111,0.473600,0.337478

In [116]:
new_df = pd.concat([combined_df.reset_index(drop=True), predictors_df.reset_index(drop=True)], axis=1)

In [117]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [118]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [119]:
%%R

require('tidyverse')
require('DescTools')

In [100]:
new_df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,result,player,w_rate_1stWon,w_bpSaved_rate,w_return_points_won,w_return_rate,l_rate_1stWon,l_bpSaved_rate,l_return_points_won,l_return_rate,w_prev_rate_1stWon_avg,l_prev_rate_1stWon_avg,w_prev_bpSaved_rate,l_prev_bpSaved_rate,w_prev_return_rate,l_prev_return_rate
0,2023-9900,United Cup,Hard,18,A,2023-01-02,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0,1,Taylor Fritz,0.865385,NaN,35.0,0.360825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.413444,NaN
1,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,270,200615,NaN,Q,Alexei Popyrin,R,196.0,AUS,23.4,200000,2.0,NaN,Felix Auger Aliassime,R,193.0,CAN,22.4,6-4 7-6(5),3,R32,114.0,11.0,2.0,67.0,45.0,35.0,13.0,11.0,1.0,2.0,7.0,2.0,66.0,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0,1,Alexei Popyrin,0.777778,0.500000,22.0,0.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.413444,NaN
2,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,271,106218,NaN,NaN,Marcos Giron,R,180.0,USA,29.4,104755,NaN,NaN,Richard Gasquet,R,183.0,FRA,36.5,7-6(5) 6-7(6) 7-5,3,R32,177.0,13.0,2.0,110.0,76.0,59.0,23.0,18.0,2.0,3.0,10.0,4.0,139.0,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0,1,Marcos Giron,0.776316,0.666667,50.0,0.359712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.413444,NaN
3,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,272,111456,NaN,NaN,Mackenzie Mcdonald,R,178.0,USA,27.7,123755,NaN,NaN,Daniel Elahi Galan,R,191.0,COL,26.5,6-3 0-0 RET,3,R32,40.0,4.0,1.0,20.0,14.0,14.0,2.0,4.0,0.0,0.0,2.0,1.0,39.0,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0,1,Mackenzie Mcdonald,1.000000,NaN,17.0,0.435897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.413444,NaN
4,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,273,106415,NaN,NaN,Yoshihito Nishioka,L,170.0,JPN,27.2,208029,5.0,NaN,Holger Rune,R,188.0,DEN,19.6,2-6 6-4 6-4,3,R32,125.0,0.0,8.0,86.0,54.0,36.0,16.0,14.0,5.0,9.0,14.0,8.0,95.0,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0,1,Yoshihito Nishioka,0.666667,0.555556,39.0,0.410526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.413444,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,290,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,4-2 2-4 4-3(7) 4-1,5,RR,108.0,13.0,2.0,74.0,45.0,35.0,15.0,12.0,6.0,7.0,4.0,3.0,70.0,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0,0,Luca Van Assche,NaN,NaN,NaN,NaN,0.674419,0.818182,24.0,0.324324,0.768321,0.667509,0.675025,0.518434,0.413444,0.306438
5968,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,286,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,3-4(6) 4-2 4-3(5) 4-2,5,RR,92.0,18.0,1.0,71.0,56.0,49.0,8.0,12.0,3.0,3.0,9.0,2.0,76.0,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0,0,Abedallah Shelbayh,NaN,NaN,NaN,NaN,0.720000,0.000000,14.0,0.197183,0.768321,0.667509,0.675025,0.518434,0.413444,0.306438
5969,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,287,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,210506,4.0,NaN,Alex Michelsen,R,193.0,USA,19.2,4-2 1-4 4-0 4-0,5,RR,67.0,7.0,2.0,51.0,34.0,25.0,10.0,9.0,3.0,4.0,2.0,1.0,55.0,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0,0,Alex Michelsen,NaN,NaN,NaN,NaN,0.594595,0.500000,16.0,0.313725,0.768321,0.667509,0.675025,0.518434,0.413444,0.306438
5970,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,289,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,4-3(5) 3-4(5) 4-1 4-1,5,RR,114.0,9.0,3.0,81.0,62.0,40.0,5.0,11.0,15.0,17.0,5.0,3.0,76.0,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0,0,Abedallah Shelbayh,NaN,NaN,NaN,NaN,0.682927,0.500000,36.0,0.444444,0.768321,0.667509,0.675025,0.518434,0.413444,0.306438
5971,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,292,208134,7.0,NaN,Luca Nardi,R,185.0,ITA,20.3,207925,5.0,NaN,Flavio Cobolli,R,183.0,ITA,21.5,3-4(4) 4-2 4-3(1) 1-4 4-3(3),5,RR,133.0,5.0,0.0,93.0,67.0,51.0,14.0,14.0,5.0,7.0,3.0,2.0,97.0,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0,0,Flavio Cobolli,NaN,NaN,NaN,NaN,0.807692,0.600000,28.0,0.301075,0.768321,0.667509,0.675025,0.518434,0.413444,0.306438

In [120]:
%%R -i new_df

logistic <- glm(result ~  w_prev_rate_1stWon_avg + l_prev_rate_1stWon_avg + w_prev_bpSaved_rate + l_prev_bpSaved_rate + w_prev_return_rate + l_prev_return_rate  , data=new_df, family="binomial")

print(summary(logistic))
print(PseudoR2(logistic, which="McFadden"))

Call:
glm(formula = result ~ w_prev_rate_1stWon_avg + l_prev_rate_1stWon_avg +
    w_prev_bpSaved_rate + l_prev_bpSaved_rate + w_prev_return_rate +
    l_prev_return_rate, family = "binomial", data = new_df)

Coefficients:
                       Estimate Std. Error z value Pr(>|z|)
(Intercept)             -6.7839     0.8589  -7.898 2.83e-15 ***
w_prev_rate_1stWon_avg   2.6986     0.7792   3.463 0.000534 ***
l_prev_rate_1stWon_avg   3.2183     0.6979   4.611 4.00e-06 ***
w_prev_bpSaved_rate      0.5014     0.2703   1.855 0.063617 .
l_prev_bpSaved_rate     -0.5382     0.3605  -1.493 0.135408
w_prev_return_rate       3.2079     0.8252   3.887 0.000101 ***
l_prev_return_rate       4.0307     0.9876   4.081 4.48e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6549.9  on 4729  degrees of freedom
Residual deviance: 6471.5  on 4723  degrees of freedom
  (1242 observations deleted due to missingness)
AIC: 6485.5

Number of Fisher Scoring iterations: 4

  McFadden
0.01196253

In [ ]:
## keep this part above intact