In [9]:
import pandas as pd 

# show all columns
pd.set_option('display.max_columns', None)

df_raw = pd.read_csv("atp_matches_2023.csv", parse_dates = ['tourney_date'])\
    .sort_values(by='tourney_date')
df_raw

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,2023-01-02,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
78,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,270,200615,NaN,Q,Alexei Popyrin,R,196.0,AUS,23.4,200000,2.0,NaN,Felix Auger Aliassime,R,193.0,CAN,22.4,6-4 7-6(5),3,R32,114.0,11.0,2.0,67.0,45.0,35.0,13.0,11.0,1.0,2.0,7.0,2.0,66.0,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0
77,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,271,106218,NaN,NaN,Marcos Giron,R,180.0,USA,29.4,104755,NaN,NaN,Richard Gasquet,R,183.0,FRA,36.5,7-6(5) 6-7(6) 7-5,3,R32,177.0,13.0,2.0,110.0,76.0,59.0,23.0,18.0,2.0,3.0,10.0,4.0,139.0,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0
76,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,272,111456,NaN,NaN,Mackenzie Mcdonald,R,178.0,USA,27.7,123755,NaN,NaN,Daniel Elahi Galan,R,191.0,COL,26.5,6-3 0-0 RET,3,R32,40.0,4.0,1.0,20.0,14.0,14.0,2.0,4.0,0.0,0.0,2.0,1.0,39.0,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0
75,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,273,106415,NaN,NaN,Yoshihito Nishioka,L,170.0,JPN,27.2,208029,5.0,NaN,Holger Rune,R,188.0,DEN,19.6,2-6 6-4 6-4,3,R32,125.0,0.0,8.0,86.0,54.0,36.0,16.0,14.0,5.0,9.0,14.0,8.0,95.0,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,290,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,4-2 2-4 4-3(7) 4-1,5,RR,108.0,13.0,2.0,74.0,45.0,35.0,15.0,12.0,6.0,7.0,4.0,3.0,70.0,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0
2765,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,286,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,3-4(6) 4-2 4-3(5) 4-2,5,RR,92.0,18.0,1.0,71.0,56.0,49.0,8.0,12.0,3.0,3.0,9.0,2.0,76.0,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0
2764,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,287,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,210506,4.0,NaN,Alex Michelsen,R,193.0,USA,19.2,4-2 1-4 4-0 4-0,5,RR,67.0,7.0,2.0,51.0,34.0,25.0,10.0,9.0,3.0,4.0,2.0,1.0,55.0,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0
2762,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,289,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,4-3(5) 3-4(5) 4-1 4-1,5,RR,114.0,9.0,3.0,81.0,62.0,40.0,5.0,11.0,15.0,17.0,5.0,3.0,76.0,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0
2759,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,292,208134,7.0,NaN,Luca Nardi,R,185.0,ITA,20.3,207925,5.0,NaN,Flavio Cobolli,R,183.0,ITA,21.5,3-4(4) 4-2 4-3(1) 1-4 4-3(3),5,RR,133.0,5.0,0.0,93.0,67.0,51.0,14.0,14.0,5.0,7.0,3.0,2.0,97.0,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0

In [19]:
from tqdm.auto import tqdm
tqdm.pandas()

In [29]:
predictors = []

for index, match in tqdm(df_raw.iterrows(), total=len(df_raw)):
    
    previous_matches = df_raw[df_raw['tourney_date'] < match['tourney_date']]

    # create a new variable
    number_of_previous_matches_won = len(previous_matches.query(f"winner_id == {match['winner_id']}"))

    # append to dataframe
    predictors.append({
        'prev_match_won': number_of_previous_matches_won
    })

pd.DataFrame(predictors)

  0%|          | 0/2986 [00:00<?, ?it/s]

      prev_match_won
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
2981               7
2982               7
2983               2
2984              10
2985               1

[2986 rows x 1 columns]

In [30]:
df_predictors = pd.DataFrame(predictors)
df_predictors

      prev_match_won
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
2981               7
2982               7
2983               2
2984              10
2985               1

[2986 rows x 1 columns]

In [31]:
df = df_raw

In [32]:
assert(len(df) == len(df_predictors))

In [33]:
pd.concat([df, df_predictors], axis=1)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,prev_match_won
0,2023-9900,United Cup,Hard,18,A,2023-01-02,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0,0
78,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,270,200615,NaN,Q,Alexei Popyrin,R,196.0,AUS,23.4,200000,2.0,NaN,Felix Auger Aliassime,R,193.0,CAN,22.4,6-4 7-6(5),3,R32,114.0,11.0,2.0,67.0,45.0,35.0,13.0,11.0,1.0,2.0,7.0,2.0,66.0,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0,0
77,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,271,106218,NaN,NaN,Marcos Giron,R,180.0,USA,29.4,104755,NaN,NaN,Richard Gasquet,R,183.0,FRA,36.5,7-6(5) 6-7(6) 7-5,3,R32,177.0,13.0,2.0,110.0,76.0,59.0,23.0,18.0,2.0,3.0,10.0,4.0,139.0,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0,0
76,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,272,111456,NaN,NaN,Mackenzie Mcdonald,R,178.0,USA,27.7,123755,NaN,NaN,Daniel Elahi Galan,R,191.0,COL,26.5,6-3 0-0 RET,3,R32,40.0,4.0,1.0,20.0,14.0,14.0,2.0,4.0,0.0,0.0,2.0,1.0,39.0,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0,0
75,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,273,106415,NaN,NaN,Yoshihito Nishioka,L,170.0,JPN,27.2,208029,5.0,NaN,Holger Rune,R,188.0,DEN,19.6,2-6 6-4 6-4,3,R32,125.0,0.0,8.0,86.0,54.0,36.0,16.0,14.0,5.0,9.0,14.0,8.0,95.0,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,290,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,4-2 2-4 4-3(7) 4-1,5,RR,108.0,13.0,2.0,74.0,45.0,35.0,15.0,12.0,6.0,7.0,4.0,3.0,70.0,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0,0
2765,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,286,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,3-4(6) 4-2 4-3(5) 4-2,5,RR,92.0,18.0,1.0,71.0,56.0,49.0,8.0,12.0,3.0,3.0,9.0,2.0,76.0,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0,25
2764,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,287,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,210506,4.0,NaN,Alex Michelsen,R,193.0,USA,19.2,4-2 1-4 4-0 4-0,5,RR,67.0,7.0,2.0,51.0,34.0,25.0,10.0,9.0,3.0,4.0,2.0,1.0,55.0,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0,18
2762,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,289,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,4-3(5) 3-4(5) 4-1 4-1,5,RR,114.0,9.0,3.0,81.0,62.0,40.0,5.0,11.0,15.0,17.0,5.0,3.0,76.0,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0,21
2759,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,292,208134,7.0,NaN,Luca Nardi,R,185.0,ITA,20.3,207925,5.0,NaN,Flavio Cobolli,R,183.0,ITA,21.5,3-4(4) 4-2 4-3(1) 1-4 4-3(3),5,RR,133.0,5.0,0.0,93.0,67.0,51.0,14.0,14.0,5.0,7.0,3.0,2.0,97.0,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0,20