In [3]:
import pandas as pd 

# show all columns
pd.set_option('display.max_columns', None)

df = pd.read_csv("atp_matches_2023.csv", parse_dates = ['tourney_date'])\
    .sort_values(by='tourney_date')
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,2023-01-02,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
78,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,270,200615,NaN,Q,Alexei Popyrin,R,196.0,AUS,23.4,200000,2.0,NaN,Felix Auger Aliassime,R,193.0,CAN,22.4,6-4 7-6(5),3,R32,114.0,11.0,2.0,67.0,45.0,35.0,13.0,11.0,1.0,2.0,7.0,2.0,66.0,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0
77,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,271,106218,NaN,NaN,Marcos Giron,R,180.0,USA,29.4,104755,NaN,NaN,Richard Gasquet,R,183.0,FRA,36.5,7-6(5) 6-7(6) 7-5,3,R32,177.0,13.0,2.0,110.0,76.0,59.0,23.0,18.0,2.0,3.0,10.0,4.0,139.0,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0
76,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,272,111456,NaN,NaN,Mackenzie Mcdonald,R,178.0,USA,27.7,123755,NaN,NaN,Daniel Elahi Galan,R,191.0,COL,26.5,6-3 0-0 RET,3,R32,40.0,4.0,1.0,20.0,14.0,14.0,2.0,4.0,0.0,0.0,2.0,1.0,39.0,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0
75,2023-2843,Adelaide 1,Hard,32,A,2023-01-02,273,106415,NaN,NaN,Yoshihito Nishioka,L,170.0,JPN,27.2,208029,5.0,NaN,Holger Rune,R,188.0,DEN,19.6,2-6 6-4 6-4,3,R32,125.0,0.0,8.0,86.0,54.0,36.0,16.0,14.0,5.0,9.0,14.0,8.0,95.0,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,290,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,4-2 2-4 4-3(7) 4-1,5,RR,108.0,13.0,2.0,74.0,45.0,35.0,15.0,12.0,6.0,7.0,4.0,3.0,70.0,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0
2765,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,286,209098,6.0,NaN,Hamad Medjedovic,R,188.0,SRB,20.3,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,3-4(6) 4-2 4-3(5) 4-2,5,RR,92.0,18.0,1.0,71.0,56.0,49.0,8.0,12.0,3.0,3.0,9.0,2.0,76.0,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0
2764,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,287,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,210506,4.0,NaN,Alex Michelsen,R,193.0,USA,19.2,4-2 1-4 4-0 4-0,5,RR,67.0,7.0,2.0,51.0,34.0,25.0,10.0,9.0,3.0,4.0,2.0,1.0,55.0,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0
2762,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,289,209414,2.0,NaN,Luca Van Assche,R,178.0,FRA,19.5,209406,8.0,NaN,Abedallah Shelbayh,L,180.0,JOR,20.0,4-3(5) 3-4(5) 4-1 4-1,5,RR,114.0,9.0,3.0,81.0,62.0,40.0,5.0,11.0,15.0,17.0,5.0,3.0,76.0,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0
2759,2023-7696,NextGen Finals,Hard,8,F,2023-11-27,292,208134,7.0,NaN,Luca Nardi,R,185.0,ITA,20.3,207925,5.0,NaN,Flavio Cobolli,R,183.0,ITA,21.5,3-4(4) 4-2 4-3(1) 1-4 4-3(3),5,RR,133.0,5.0,0.0,93.0,67.0,51.0,14.0,14.0,5.0,7.0,3.0,2.0,97.0,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0

In [5]:
import pandas as pd
import numpy as np

def transform_tennis_data(input_file, output_file=None):
    """
    Transform tennis match data from winner/loser format to player A/B format.
    Using random assignment for player A and B.
    
    Parameters:
    input_file (str): Path to the input CSV file
    output_file (str, optional): Path to the output CSV file. If None, no file is saved.
    """
    # Read the CSV file
    df = pd.read_csv("atp_matches_2023.csv")
    
    # Use random assignment for player A and B
    np.random.seed(42)  # For reproducibility
    winner_is_A = np.random.randint(0, 2, size=len(df)) == 1
    
    # Create a new dataframe for the transformed data
    result_df = pd.DataFrame()
    
    # Copy non-player columns directly
    non_player_cols = [col for col in df.columns if not (col.startswith('winner_') or 
                                                       col.startswith('loser_') or 
                                                       col.startswith('w_') or 
                                                       col.startswith('l_'))]
    for col in non_player_cols:
        result_df[col] = df[col]
    
    # Map player attributes
    player_attributes = [
        ('id', 'winner_id', 'loser_id'),
        ('seed', 'winner_seed', 'loser_seed'),
        ('entry', 'winner_entry', 'loser_entry'),
        ('name', 'winner_name', 'loser_name'),
        ('hand', 'winner_hand', 'loser_hand'),
        ('ht', 'winner_ht', 'loser_ht'),
        ('ioc', 'winner_ioc', 'loser_ioc'),
        ('age', 'winner_age', 'loser_age'),
        ('rank', 'winner_rank', 'loser_rank'),
        ('rank_points', 'winner_rank_points', 'loser_rank_points')
    ]
    
    for attr, winner_col, loser_col in player_attributes:
        result_df[f'player_A_{attr}'] = np.where(winner_is_A, df[winner_col], df[loser_col])
        result_df[f'player_B_{attr}'] = np.where(winner_is_A, df[loser_col], df[winner_col])
    
    # Map player statistics
    player_stats = [
        ('ace', 'w_ace', 'l_ace'),
        ('df', 'w_df', 'l_df'),
        ('svpt', 'w_svpt', 'l_svpt'),
        ('1stIn', 'w_1stIn', 'l_1stIn'),
        ('1stWon', 'w_1stWon', 'l_1stWon'),
        ('2ndWon', 'w_2ndWon', 'l_2ndWon'),
        ('SvGms', 'w_SvGms', 'l_SvGms'),
        ('bpSaved', 'w_bpSaved', 'l_bpSaved'),
        ('bpFaced', 'w_bpFaced', 'l_bpFaced')
    ]
    
    for stat, winner_col, loser_col in player_stats:
        result_df[f'player_A_{stat}'] = np.where(winner_is_A, df[winner_col], df[loser_col])
        result_df[f'player_B_{stat}'] = np.where(winner_is_A, df[loser_col], df[winner_col])
    
    # Add winner column 
    result_df['winner'] = np.where(winner_is_A, 'A', 'B')
    
    # Add player_A_win column (0 or 1)
    result_df['player_A_win'] = winner_is_A.astype(int)
    
    # Save the transformed data if output_file is provided
    if output_file:
        result_df.to_csv(output_file, index=False)
    
    return result_df

# Example usage with random assignment
df_transformed = transform_tennis_data('atp_matches_2023.csv', 'atp_matches_2023_transformed.csv')
df_transformed
df = df_transformed
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,score,best_of,round,minutes,player_A_id,player_B_id,player_A_seed,player_B_seed,player_A_entry,player_B_entry,player_A_name,player_B_name,player_A_hand,player_B_hand,player_A_ht,player_B_ht,player_A_ioc,player_B_ioc,player_A_age,player_B_age,player_A_rank,player_B_rank,player_A_rank_points,player_B_rank_points,player_A_ace,player_B_ace,player_A_df,player_B_df,player_A_svpt,player_B_svpt,player_A_1stIn,player_B_1stIn,player_A_1stWon,player_B_1stWon,player_A_2ndWon,player_B_2ndWon,player_A_SvGms,player_B_SvGms,player_A_bpSaved,player_B_bpSaved,player_A_bpFaced,player_B_bpFaced,winner,player_A_win
0,2023-9900,United Cup,Hard,18,A,20230102,300,7-6(4) 7-6(6),3,F,135.0,126610,126203,5.0,3.0,NaN,NaN,Matteo Berrettini,Taylor Fritz,R,R,196.0,196.0,ITA,USA,26.7,25.1,16.0,9.0,2375.0,3355.0,7.0,15.0,2.0,2.0,97.0,85.0,62.0,52.0,47.0,45.0,15.0,16.0,12.0,12.0,9.0,0.0,9.0,0.0,B,0
1,2023-9900,United Cup,Hard,18,A,20230102,299,6-2 0-0 RET,3,F,34.0,126207,207518,NaN,NaN,NaN,NaN,Frances Tiafoe,Lorenzo Musetti,R,R,188.0,185.0,USA,ITA,24.9,20.8,19.0,23.0,2000.0,1865.0,3.0,0.0,1.0,0.0,27.0,21.0,19.0,12.0,15.0,8.0,3.0,3.0,4.0,4.0,3.0,1.0,3.0,3.0,A,1
2,2023-9900,United Cup,Hard,18,A,20230102,296,7-6(5) 7-6(5),3,SF,104.0,128034,126203,2.0,3.0,NaN,NaN,Hubert Hurkacz,Taylor Fritz,R,R,196.0,196.0,POL,USA,25.8,25.1,10.0,9.0,2905.0,3355.0,17.0,11.0,1.0,0.0,82.0,80.0,62.0,50.0,51.0,44.0,7.0,19.0,12.0,12.0,2.0,4.0,2.0,4.0,B,0
3,2023-9900,United Cup,Hard,18,A,20230102,295,6-3 6-3,3,SF,79.0,200390,126207,NaN,NaN,NaN,NaN,Kacper Zuk,Frances Tiafoe,R,R,183.0,188.0,POL,USA,23.9,24.9,245.0,19.0,220.0,2000.0,3.0,5.0,3.0,4.0,68.0,61.0,41.0,37.0,26.0,31.0,12.0,11.0,9.0,9.0,6.0,5.0,9.0,5.0,B,0
4,2023-9900,United Cup,Hard,18,A,20230102,292,4-6 7-6(2) 6-4,3,SF,155.0,126610,126774,5.0,1.0,NaN,NaN,Matteo Berrettini,Stefanos Tsitsipas,R,R,196.0,193.0,ITA,GRE,26.7,24.3,16.0,4.0,2375.0,5550.0,7.0,9.0,2.0,1.0,89.0,98.0,58.0,52.0,48.0,43.0,18.0,28.0,16.0,16.0,1.0,1.0,2.0,2.0,B,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2981,2023-M-DC-2023-WG2-PO-RSA-LUX-01,Davis Cup WG2 PO: RSA vs LUX,NaN,4,D,20230204,5,6-4 7-5,3,RR,NaN,202335,209280,NaN,NaN,NaN,NaN,Raphael Calzi,Devin Badenhorst,R,R,180.0,NaN,LUX,RSA,25.5,18.6,NaN,1717.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1
2982,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,1,6-4 7-6(4),3,RR,NaN,109734,117365,NaN,NaN,NaN,NaN,Skander Mansouri,Petros Chrysochos,R,R,193.0,185.0,TUN,CYP,27.5,26.8,279.0,990.0,190.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0
2983,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,2,6-1 3-6 6-2,3,RR,NaN,144949,121411,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Moez Echargui,R,R,183.0,178.0,CYP,TUN,23.9,30.0,894.0,364.0,15.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0
2984,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,4,3-6 6-1 6-4,3,RR,NaN,144949,144826,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Aziz Dougaz,R,L,183.0,188.0,CYP,TUN,23.9,25.8,894.0,285.0,15.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1
2985,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,5,7-6(5) 7-5,3,RR,NaN,121411,117365,NaN,NaN,NaN,NaN,Moez Echargui,Petros Chrysochos,R,R,178.0,185.0,TUN,CYP,30.0,26.8,364.0,990.0,131.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2986 entries, 0 to 2985
Data columns (total 51 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   tourney_id            2986 non-null   object
 1   tourney_name          2986 non-null   object
 2   surface               2933 non-null   object
 3   draw_size             2986 non-null   int64
 4   tourney_level         2986 non-null   object
 5   tourney_date          2986 non-null   int64
 6   match_num             2986 non-null   int64
 7   score                 2986 non-null   object
 8   best_of               2986 non-null   int64
 9   round                 2986 non-null   object
 10  minutes               2754 non-null   float64
 11  player_A_id           2986 non-null   int64
 12  player_B_id           2986 non-null   int64
 13  player_A_seed         1024 non-null   float64
 14  player_B_seed         995 non-null    float64
 15  player_A_entry        583 non-null    object
 16  player_B_entry        585 non-null    object
 17  player_A_name         2986 non-null   object
 18  player_B_name         2986 non-null   object
 19  player_A_hand         2986 non-null   object
 20  player_B_hand         2986 non-null   object
 21  player_A_ht           2957 non-null   float64
 22  player_B_ht           2966 non-null   float64
 23  player_A_ioc          2986 non-null   object
 24  player_B_ioc          2986 non-null   object
 25  player_A_age          2985 non-null   float64
 26  player_B_age          2985 non-null   float64
 27  player_A_rank         2958 non-null   float64
 28  player_B_rank         2961 non-null   float64
 29  player_A_rank_points  2958 non-null   float64
 30  player_B_rank_points  2961 non-null   float64
 31  player_A_ace          2815 non-null   float64
 32  player_B_ace          2815 non-null   float64
 33  player_A_df           2815 non-null   float64
 34  player_B_df           2815 non-null   float64
 35  player_A_svpt         2815 non-null   float64
 36  player_B_svpt         2815 non-null   float64
 37  player_A_1stIn        2815 non-null   float64
 38  player_B_1stIn        2815 non-null   float64
 39  player_A_1stWon       2815 non-null   float64
 40  player_B_1stWon       2815 non-null   float64
 41  player_A_2ndWon       2815 non-null   float64
 42  player_B_2ndWon       2815 non-null   float64
 43  player_A_SvGms        2815 non-null   float64
 44  player_B_SvGms        2815 non-null   float64
 45  player_A_bpSaved      2815 non-null   float64
 46  player_B_bpSaved      2815 non-null   float64
 47  player_A_bpFaced      2815 non-null   float64
 48  player_B_bpFaced      2815 non-null   float64
 49  winner                2986 non-null   object
 50  player_A_win          2986 non-null   int64
dtypes: float64(29), int64(7), object(15)
memory usage: 1.2+ MB

In [22]:

#calculating rate of 1st serves won
df['player_A_rate_1stWon'] = df['player_A_1stWon'] / df['player_A_1stIn'].replace(0, pd.NA)

#calculating rate of break points saved (stat explained in memo)
df['player_A_bpSaved_rate'] = df['player_A_bpSaved'] / df['player_A_bpFaced'].replace(0, pd.NA)

# for every player, i also want return points stats, and these I will get from the loser's service points stats
df['player_A_return_points_won'] = df['player_B_svpt'] - df['player_B_1stWon'] - df['player_B_2ndWon'] #calculating how many return points they faced
df['player_A_return_rate'] = df['player_A_return_points_won'] / df['player_B_svpt'].replace(0, pd.NA) #rate of return points won by winner


#Doing the same calculation for the matches the players lost
df['player_B_rate_1stWon'] = df['player_B_1stWon'] / df['player_B_1stIn'].replace(0, pd.NA)
df['player_B_bpSaved_rate'] = df['player_B_bpSaved'] / df['player_B_bpFaced'].replace(0, pd.NA)
df['player_B_return_points_won'] = df['player_A_svpt'] - df['player_A_1stWon'] - df['player_A_2ndWon']
df['player_B_return_rate'] = df['player_B_return_points_won'] / df['player_B_svpt'].replace(0, pd.NA)

#combining the two dataframes so now i have a new dataset of all top 20 players and the matches they won and lost in 2023
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,score,best_of,round,minutes,player_A_id,player_B_id,player_A_seed,player_B_seed,player_A_entry,player_B_entry,player_A_name,player_B_name,player_A_hand,player_B_hand,player_A_ht,player_B_ht,player_A_ioc,player_B_ioc,player_A_age,player_B_age,player_A_rank,player_B_rank,player_A_rank_points,player_B_rank_points,player_A_ace,player_B_ace,player_A_df,player_B_df,player_A_svpt,player_B_svpt,player_A_1stIn,player_B_1stIn,player_A_1stWon,player_B_1stWon,player_A_2ndWon,player_B_2ndWon,player_A_SvGms,player_B_SvGms,player_A_bpSaved,player_B_bpSaved,player_A_bpFaced,player_B_bpFaced,winner,player_A_win,player_A_rate_1stWon,player_A_bpSaved_rate,player_A_return_points_won,player_A_return_rate,player_B_rate_1stWon,player_B_bpSaved_rate,player_B_return_points_won,player_B_return_rate
0,2023-9900,United Cup,Hard,18,A,20230102,300,7-6(4) 7-6(6),3,F,135.0,126610,126203,5.0,3.0,NaN,NaN,Matteo Berrettini,Taylor Fritz,R,R,196.0,196.0,ITA,USA,26.7,25.1,16.0,9.0,2375.0,3355.0,7.0,15.0,2.0,2.0,97.0,85.0,62.0,52.0,47.0,45.0,15.0,16.0,12.0,12.0,9.0,0.0,9.0,0.0,B,0,0.758065,1.0,24.0,0.282353,0.865385,<NA>,35.0,0.411765
1,2023-9900,United Cup,Hard,18,A,20230102,299,6-2 0-0 RET,3,F,34.0,126207,207518,NaN,NaN,NaN,NaN,Frances Tiafoe,Lorenzo Musetti,R,R,188.0,185.0,USA,ITA,24.9,20.8,19.0,23.0,2000.0,1865.0,3.0,0.0,1.0,0.0,27.0,21.0,19.0,12.0,15.0,8.0,3.0,3.0,4.0,4.0,3.0,1.0,3.0,3.0,A,1,0.789474,1.0,10.0,0.476190,0.666667,0.333333,9.0,0.428571
2,2023-9900,United Cup,Hard,18,A,20230102,296,7-6(5) 7-6(5),3,SF,104.0,128034,126203,2.0,3.0,NaN,NaN,Hubert Hurkacz,Taylor Fritz,R,R,196.0,196.0,POL,USA,25.8,25.1,10.0,9.0,2905.0,3355.0,17.0,11.0,1.0,0.0,82.0,80.0,62.0,50.0,51.0,44.0,7.0,19.0,12.0,12.0,2.0,4.0,2.0,4.0,B,0,0.822581,1.0,17.0,0.212500,0.880000,1.0,24.0,0.300000
3,2023-9900,United Cup,Hard,18,A,20230102,295,6-3 6-3,3,SF,79.0,200390,126207,NaN,NaN,NaN,NaN,Kacper Zuk,Frances Tiafoe,R,R,183.0,188.0,POL,USA,23.9,24.9,245.0,19.0,220.0,2000.0,3.0,5.0,3.0,4.0,68.0,61.0,41.0,37.0,26.0,31.0,12.0,11.0,9.0,9.0,6.0,5.0,9.0,5.0,B,0,0.634146,0.666667,19.0,0.311475,0.837838,1.0,30.0,0.491803
4,2023-9900,United Cup,Hard,18,A,20230102,292,4-6 7-6(2) 6-4,3,SF,155.0,126610,126774,5.0,1.0,NaN,NaN,Matteo Berrettini,Stefanos Tsitsipas,R,R,196.0,193.0,ITA,GRE,26.7,24.3,16.0,4.0,2375.0,5550.0,7.0,9.0,2.0,1.0,89.0,98.0,58.0,52.0,48.0,43.0,18.0,28.0,16.0,16.0,1.0,1.0,2.0,2.0,B,0,0.827586,0.5,27.0,0.275510,0.826923,0.5,23.0,0.234694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2981,2023-M-DC-2023-WG2-PO-RSA-LUX-01,Davis Cup WG2 PO: RSA vs LUX,NaN,4,D,20230204,5,6-4 7-5,3,RR,NaN,202335,209280,NaN,NaN,NaN,NaN,Raphael Calzi,Devin Badenhorst,R,R,180.0,NaN,LUX,RSA,25.5,18.6,NaN,1717.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,1,6-4 7-6(4),3,RR,NaN,109734,117365,NaN,NaN,NaN,NaN,Skander Mansouri,Petros Chrysochos,R,R,193.0,185.0,TUN,CYP,27.5,26.8,279.0,990.0,190.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,2,6-1 3-6 6-2,3,RR,NaN,144949,121411,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Moez Echargui,R,R,183.0,178.0,CYP,TUN,23.9,30.0,894.0,364.0,15.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2984,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,4,3-6 6-1 6-4,3,RR,NaN,144949,144826,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Aziz Dougaz,R,L,183.0,188.0,CYP,TUN,23.9,25.8,894.0,285.0,15.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,5,7-6(5) 7-5,3,RR,NaN,121411,117365,NaN,NaN,NaN,NaN,Moez Echargui,Petros Chrysochos,R,R,178.0,185.0,TUN,CYP,30.0,26.8,364.0,990.0,131.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
from tqdm.auto import tqdm
tqdm.pandas()

In [26]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2986 entries, 0 to 2985
Data columns (total 65 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tourney_id                     2986 non-null   object
 1   tourney_name                   2986 non-null   object
 2   surface                        2933 non-null   object
 3   draw_size                      2986 non-null   int64
 4   tourney_level                  2986 non-null   object
 5   tourney_date                   2986 non-null   int64
 6   match_num                      2986 non-null   int64
 7   score                          2986 non-null   object
 8   best_of                        2986 non-null   int64
 9   round                          2986 non-null   object
 10  minutes                        2754 non-null   float64
 11  player_A_id                    2986 non-null   int64
 12  player_B_id                    2986 non-null   int64
 13  player_A_seed                  1024 non-null   float64
 14  player_B_seed                  995 non-null    float64
 15  player_A_entry                 583 non-null    object
 16  player_B_entry                 585 non-null    object
 17  player_A_name                  2986 non-null   object
 18  player_B_name                  2986 non-null   object
 19  player_A_hand                  2986 non-null   object
 20  player_B_hand                  2986 non-null   object
 21  player_A_ht                    2957 non-null   float64
 22  player_B_ht                    2966 non-null   float64
 23  player_A_ioc                   2986 non-null   object
 24  player_B_ioc                   2986 non-null   object
 25  player_A_age                   2985 non-null   float64
 26  player_B_age                   2985 non-null   float64
 27  player_A_rank                  2958 non-null   float64
 28  player_B_rank                  2961 non-null   float64
 29  player_A_rank_points           2958 non-null   float64
 30  player_B_rank_points           2961 non-null   float64
 31  player_A_ace                   2815 non-null   float64
 32  player_B_ace                   2815 non-null   float64
 33  player_A_df                    2815 non-null   float64
 34  player_B_df                    2815 non-null   float64
 35  player_A_svpt                  2815 non-null   float64
 36  player_B_svpt                  2815 non-null   float64
 37  player_A_1stIn                 2815 non-null   float64
 38  player_B_1stIn                 2815 non-null   float64
 39  player_A_1stWon                2815 non-null   float64
 40  player_B_1stWon                2815 non-null   float64
 41  player_A_2ndWon                2815 non-null   float64
 42  player_B_2ndWon                2815 non-null   float64
 43  player_A_SvGms                 2815 non-null   float64
 44  player_B_SvGms                 2815 non-null   float64
 45  player_A_bpSaved               2815 non-null   float64
 46  player_B_bpSaved               2815 non-null   float64
 47  player_A_bpFaced               2815 non-null   float64
 48  player_B_bpFaced               2815 non-null   float64
 49  winner                         2986 non-null   object
 50  player_A_win                   2986 non-null   int64
 51  player_A_rate_1stWon           2815 non-null   float64
 52  player_A_bpSaved_rate          2675 non-null   object
 53  player_A_return_points_won     2815 non-null   float64
 54  player_A_return_rate           2815 non-null   float64
 55  player_B_rate_1stWon           2815 non-null   float64
 56  player_B_bpSaved_rate          2683 non-null   object
 57  player_B_return_points_won     2815 non-null   float64
 58  player_B_return_rate           2815 non-null   float64
 59  player_A_prev_rate_1stWon_avg  2880 non-null   float64
 60  player_B_prev_rate_1stWon_avg  2880 non-null   float64
 61  player_A_prev_bpSaved_rate     2880 non-null   float64
 62  player_B_prev_bpSaved_rate     2880 non-null   float64
 63  player_A_prev_return_rate      2880 non-null   float64
 64  player_B_prev_return_rate      2880 non-null   float64
dtypes: float64(41), int64(7), object(17)
memory usage: 1.5+ MB

In [27]:
predictors = []

for index, match in tqdm(df.iterrows(), total=len(df)):

    match_date = match['tourney_date']
    
    # Filter all matches that happened before this one
    # player = match['player']
    previous_matches = df[
        (df['tourney_date'] < match_date)
        # (combined_df['player'] == player)
        ]

    
    # Count previous wins using the 'result' column
    

    # Average rate_1stWon from previous matches. taking the mean value because count or sum will not be right, like for the previous one 
    player_A_rate_1stWon_so_far = previous_matches['player_A_rate_1stWon'].mean(skipna=True) or 0
    player_B_rate_1stWon_so_far = previous_matches['player_B_rate_1stWon'].mean(skipna=True) or 0
    # avg_rate_1stWon_so_far = avg_rate_1stWon_so_far if not pd.isna(avg_rate_1stWon_so_far) else 0

    #same for bpSaved_rate from previous matches
    player_A_bpSaved_rate_so_far = previous_matches['player_A_bpSaved_rate'].mean(skipna=True) or 0
    player_B_bpSaved_rate_so_far = previous_matches['player_B_bpSaved_rate'].mean(skipna=True) or 0
    # avg_bpSaved_rate_so_far = avg_bpSaved_rate_so_far if not pd.isna(avg_bpSaved_rate_so_far) else 0

    #same for return_rate
    player_A_return_rate_so_far = previous_matches['player_A_return_rate'].mean(skipna=True) or 0
    player_B_return_rate_so_far = previous_matches['player_B_return_rate'].mean(skipna=True) or 0
    # avg_return_rate_so_far = avg_return_rate_so_far if not pd.isna(avg_return_rate_so_far) else 0

    predictors.append({
       'player_A_prev_rate_1stWon_avg': player_A_rate_1stWon_so_far,
        'player_B_prev_rate_1stWon_avg': player_B_rate_1stWon_so_far,
        'player_A_prev_bpSaved_rate': player_A_bpSaved_rate_so_far,
        'player_B_prev_bpSaved_rate': player_B_bpSaved_rate_so_far,
        'player_A_prev_return_rate': player_A_return_rate_so_far,
        'player_B_prev_return_rate': player_B_return_rate_so_far,   
    })

predictors_df = pd.DataFrame(predictors)
predictors_df

  0%|          | 0/2986 [00:00<?, ?it/s]

,player_A_prev_rate_1stWon_avg,player_B_prev_rate_1stWon_avg,player_A_prev_bpSaved_rate,player_B_prev_bpSaved_rate,player_A_prev_return_rate,player_B_prev_return_rate
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2981,0.733183,0.719795,0.605140,0.604752,0.356029,0.357317
2982,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2983,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2984,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2985,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537

In [29]:
new_df = pd.concat([df.reset_index(drop=True), predictors_df.reset_index(drop=True)], axis=1)
new_df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,score,best_of,round,minutes,player_A_id,player_B_id,player_A_seed,player_B_seed,player_A_entry,player_B_entry,player_A_name,player_B_name,player_A_hand,player_B_hand,player_A_ht,player_B_ht,player_A_ioc,player_B_ioc,player_A_age,player_B_age,player_A_rank,player_B_rank,player_A_rank_points,player_B_rank_points,player_A_ace,player_B_ace,player_A_df,player_B_df,player_A_svpt,player_B_svpt,player_A_1stIn,player_B_1stIn,player_A_1stWon,player_B_1stWon,player_A_2ndWon,player_B_2ndWon,player_A_SvGms,player_B_SvGms,player_A_bpSaved,player_B_bpSaved,player_A_bpFaced,player_B_bpFaced,winner,player_A_win,player_A_rate_1stWon,player_A_bpSaved_rate,player_A_return_points_won,player_A_return_rate,player_B_rate_1stWon,player_B_bpSaved_rate,player_B_return_points_won,player_B_return_rate,player_A_prev_rate_1stWon_avg,player_B_prev_rate_1stWon_avg,player_A_prev_bpSaved_rate,player_B_prev_bpSaved_rate,player_A_prev_return_rate,player_B_prev_return_rate
0,2023-9900,United Cup,Hard,18,A,20230102,300,7-6(4) 7-6(6),3,F,135.0,126610,126203,5.0,3.0,NaN,NaN,Matteo Berrettini,Taylor Fritz,R,R,196.0,196.0,ITA,USA,26.7,25.1,16.0,9.0,2375.0,3355.0,7.0,15.0,2.0,2.0,97.0,85.0,62.0,52.0,47.0,45.0,15.0,16.0,12.0,12.0,9.0,0.0,9.0,0.0,B,0,0.758065,1.0,24.0,0.282353,0.865385,<NA>,35.0,0.411765,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-9900,United Cup,Hard,18,A,20230102,299,6-2 0-0 RET,3,F,34.0,126207,207518,NaN,NaN,NaN,NaN,Frances Tiafoe,Lorenzo Musetti,R,R,188.0,185.0,USA,ITA,24.9,20.8,19.0,23.0,2000.0,1865.0,3.0,0.0,1.0,0.0,27.0,21.0,19.0,12.0,15.0,8.0,3.0,3.0,4.0,4.0,3.0,1.0,3.0,3.0,A,1,0.789474,1.0,10.0,0.476190,0.666667,0.333333,9.0,0.428571,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-9900,United Cup,Hard,18,A,20230102,296,7-6(5) 7-6(5),3,SF,104.0,128034,126203,2.0,3.0,NaN,NaN,Hubert Hurkacz,Taylor Fritz,R,R,196.0,196.0,POL,USA,25.8,25.1,10.0,9.0,2905.0,3355.0,17.0,11.0,1.0,0.0,82.0,80.0,62.0,50.0,51.0,44.0,7.0,19.0,12.0,12.0,2.0,4.0,2.0,4.0,B,0,0.822581,1.0,17.0,0.212500,0.880000,1.0,24.0,0.300000,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-9900,United Cup,Hard,18,A,20230102,295,6-3 6-3,3,SF,79.0,200390,126207,NaN,NaN,NaN,NaN,Kacper Zuk,Frances Tiafoe,R,R,183.0,188.0,POL,USA,23.9,24.9,245.0,19.0,220.0,2000.0,3.0,5.0,3.0,4.0,68.0,61.0,41.0,37.0,26.0,31.0,12.0,11.0,9.0,9.0,6.0,5.0,9.0,5.0,B,0,0.634146,0.666667,19.0,0.311475,0.837838,1.0,30.0,0.491803,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-9900,United Cup,Hard,18,A,20230102,292,4-6 7-6(2) 6-4,3,SF,155.0,126610,126774,5.0,1.0,NaN,NaN,Matteo Berrettini,Stefanos Tsitsipas,R,R,196.0,193.0,ITA,GRE,26.7,24.3,16.0,4.0,2375.0,5550.0,7.0,9.0,2.0,1.0,89.0,98.0,58.0,52.0,48.0,43.0,18.0,28.0,16.0,16.0,1.0,1.0,2.0,2.0,B,0,0.827586,0.5,27.0,0.275510,0.826923,0.5,23.0,0.234694,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2981,2023-M-DC-2023-WG2-PO-RSA-LUX-01,Davis Cup WG2 PO: RSA vs LUX,NaN,4,D,20230204,5,6-4 7-5,3,RR,NaN,202335,209280,NaN,NaN,NaN,NaN,Raphael Calzi,Devin Badenhorst,R,R,180.0,NaN,LUX,RSA,25.5,18.6,NaN,1717.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.733183,0.719795,0.605140,0.604752,0.356029,0.357317
2982,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,1,6-4 7-6(4),3,RR,NaN,109734,117365,NaN,NaN,NaN,NaN,Skander Mansouri,Petros Chrysochos,R,R,193.0,185.0,TUN,CYP,27.5,26.8,279.0,990.0,190.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2983,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,2,6-1 3-6 6-2,3,RR,NaN,144949,121411,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Moez Echargui,R,R,183.0,178.0,CYP,TUN,23.9,30.0,894.0,364.0,15.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2984,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,4,3-6 6-1 6-4,3,RR,NaN,144949,144826,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Aziz Dougaz,R,L,183.0,188.0,CYP,TUN,23.9,25.8,894.0,285.0,15.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2985,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,5,7-6(5) 7-5,3,RR,NaN,121411,117365,NaN,NaN,NaN,NaN,Moez Echargui,Petros Chrysochos,R,R,178.0,185.0,TUN,CYP,30.0,26.8,364.0,990.0,131.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537

In [31]:
cols_to_check = [
    'player_A_prev_rate_1stWon_avg',
    'player_B_prev_rate_1stWon_avg',
    'player_A_prev_bpSaved_rate',
    'player_B_prev_bpSaved_rate',
    'player_A_prev_return_rate',
    'player_B_prev_return_rate'
]

new_df_cleaned = new_df.dropna(subset=cols_to_check)
new_df_cleaned

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,score,best_of,round,minutes,player_A_id,player_B_id,player_A_seed,player_B_seed,player_A_entry,player_B_entry,player_A_name,player_B_name,player_A_hand,player_B_hand,player_A_ht,player_B_ht,player_A_ioc,player_B_ioc,player_A_age,player_B_age,player_A_rank,player_B_rank,player_A_rank_points,player_B_rank_points,player_A_ace,player_B_ace,player_A_df,player_B_df,player_A_svpt,player_B_svpt,player_A_1stIn,player_B_1stIn,player_A_1stWon,player_B_1stWon,player_A_2ndWon,player_B_2ndWon,player_A_SvGms,player_B_SvGms,player_A_bpSaved,player_B_bpSaved,player_A_bpFaced,player_B_bpFaced,winner,player_A_win,player_A_rate_1stWon,player_A_bpSaved_rate,player_A_return_points_won,player_A_return_rate,player_B_rate_1stWon,player_B_bpSaved_rate,player_B_return_points_won,player_B_return_rate,player_A_prev_rate_1stWon_avg,player_B_prev_rate_1stWon_avg,player_A_prev_bpSaved_rate,player_B_prev_bpSaved_rate,player_A_prev_return_rate,player_B_prev_return_rate
106,2023-0301,Auckland,Hard,32,A,20230109,300,4-6 6-4 6-4,3,F,147.0,104755,111815,NaN,2.0,NaN,NaN,Richard Gasquet,Cameron Norrie,R,L,183.0,188.0,FRA,GBR,36.5,27.3,67.0,12.0,740.0,2575.0,3.0,8.0,2.0,2.0,88.0,86.0,44.0,52.0,36.0,36.0,21.0,17.0,15.0,15.0,6.0,4.0,9.0,8.0,A,1,0.818182,0.666667,33.0,0.383721,0.692308,0.5,31.0,0.360465,0.747678,0.720659,0.604100,0.581625,0.357665,0.343396
107,2023-0301,Auckland,Hard,32,A,20230109,299,W/O,3,SF,0.0,104755,106005,NaN,NaN,NaN,NaN,Richard Gasquet,Constant Lestienne,R,R,183.0,180.0,FRA,FRA,36.5,30.6,67.0,65.0,740.0,760.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.747678,0.720659,0.604100,0.581625,0.357665,0.343396
108,2023-0301,Auckland,Hard,32,A,20230109,298,6-3 6-4,3,SF,98.0,111815,202385,2.0,NaN,NaN,NaN,Cameron Norrie,Jenson Brooksby,L,R,188.0,188.0,GBR,USA,27.3,22.2,12.0,48.0,2575.0,920.0,3.0,4.0,0.0,0.0,48.0,73.0,31.0,43.0,27.0,26.0,11.0,14.0,10.0,9.0,3.0,6.0,4.0,9.0,A,1,0.870968,0.75,33.0,0.452055,0.604651,0.666667,10.0,0.136986,0.747678,0.720659,0.604100,0.581625,0.357665,0.343396
109,2023-0301,Auckland,Hard,32,A,20230109,297,2-6 7-6(2) 7-5,3,QF,166.0,111513,106005,NaN,NaN,NaN,NaN,Laslo Djere,Constant Lestienne,R,R,188.0,180.0,SRB,FRA,27.6,30.6,70.0,65.0,713.0,760.0,8.0,5.0,3.0,1.0,109.0,118.0,61.0,77.0,47.0,54.0,21.0,19.0,16.0,16.0,2.0,14.0,5.0,18.0,B,0,0.770492,0.4,45.0,0.381356,0.701299,0.777778,41.0,0.347458,0.747678,0.720659,0.604100,0.581625,0.357665,0.343396
110,2023-0301,Auckland,Hard,32,A,20230109,296,1-6 6-1 6-1,3,QF,94.0,104755,105676,NaN,NaN,NaN,NaN,Richard Gasquet,David Goffin,R,R,183.0,180.0,FRA,BEL,36.5,32.0,67.0,53.0,740.0,870.0,6.0,8.0,3.0,2.0,61.0,64.0,37.0,37.0,26.0,20.0,10.0,9.0,11.0,10.0,0.0,7.0,4.0,13.0,A,1,0.702703,0.0,35.0,0.546875,0.540541,0.538462,25.0,0.390625,0.747678,0.720659,0.604100,0.581625,0.357665,0.343396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2981,2023-M-DC-2023-WG2-PO-RSA-LUX-01,Davis Cup WG2 PO: RSA vs LUX,NaN,4,D,20230204,5,6-4 7-5,3,RR,NaN,202335,209280,NaN,NaN,NaN,NaN,Raphael Calzi,Devin Badenhorst,R,R,180.0,NaN,LUX,RSA,25.5,18.6,NaN,1717.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.733183,0.719795,0.605140,0.604752,0.356029,0.357317
2982,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,1,6-4 7-6(4),3,RR,NaN,109734,117365,NaN,NaN,NaN,NaN,Skander Mansouri,Petros Chrysochos,R,R,193.0,185.0,TUN,CYP,27.5,26.8,279.0,990.0,190.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2983,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,2,6-1 3-6 6-2,3,RR,NaN,144949,121411,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Moez Echargui,R,R,183.0,178.0,CYP,TUN,23.9,30.0,894.0,364.0,15.0,131.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2984,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,4,3-6 6-1 6-4,3,RR,NaN,144949,144826,NaN,NaN,NaN,NaN,Menelaos Efstathiou,Aziz Dougaz,R,L,183.0,188.0,CYP,TUN,23.9,25.8,894.0,285.0,15.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537
2985,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,5,7-6(5) 7-5,3,RR,NaN,121411,117365,NaN,NaN,NaN,NaN,Moez Echargui,Petros Chrysochos,R,R,178.0,185.0,TUN,CYP,30.0,26.8,364.0,990.0,131.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.732931,0.721203,0.604194,0.609037,0.354330,0.357537

In [32]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [33]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [34]:
%%R

require('tidyverse')
require('DescTools')

In [35]:
%%R -i new_df_cleaned

logistic <- glm(player_A_win ~  player_A_prev_rate_1stWon_avg + player_B_prev_rate_1stWon_avg + 
                player_A_prev_bpSaved_rate + player_B_prev_bpSaved_rate + player_A_prev_return_rate + player_B_prev_return_rate  , data=new_df, family="binomial")

print(summary(logistic))
print(PseudoR2(logistic, which="McFadden"))

Call:
glm(formula = player_A_win ~ player_A_prev_rate_1stWon_avg +
    player_B_prev_rate_1stWon_avg + player_A_prev_bpSaved_rate +
    player_B_prev_bpSaved_rate + player_A_prev_return_rate +
    player_B_prev_return_rate, family = "binomial", data = new_df)

Coefficients:
                              Estimate Std. Error z value Pr(>|z|)
(Intercept)                     55.909     60.583   0.923    0.356
player_A_prev_rate_1stWon_avg  -45.942     30.980  -1.483    0.138
player_B_prev_rate_1stWon_avg   11.953     36.014   0.332    0.740
player_A_prev_bpSaved_rate      -3.200     12.616  -0.254    0.800
player_B_prev_bpSaved_rate      -5.006     13.102  -0.382    0.702
player_A_prev_return_rate      -30.523     48.407  -0.631    0.528
player_B_prev_return_rate      -42.166     35.490  -1.188    0.235

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3991.5  on 2879  degrees of freedom
Residual deviance: 3987.4  on 2873  degrees of freedom
  (106 observations deleted due to missingness)
AIC: 4001.4

Number of Fisher Scoring iterations: 3

   McFadden
0.001043211

In [ ]:
%%R -i new_df

logistic_model <- glm(player_A_win ~ surface +